<?php
/**
 * Timezone array.
 *
 * @package SweetRice
 * @Dashboard core
 * @since 1.4.1
 */
 defined('VALID_INCLUDE') or die();
 return array('Australia/Darwin'=>'AUS Central Standard Time (Australia/Darwin)',
'Australia/Sydney'=>'AUS Eastern Standard Time (Australia/Sydney)',
'Asia/Kabul'=>'Afghanistan Standard Time (Asia/Kabul)',
'America/Anchorage'=>'Alaskan Standard Time (America/Anchorage)',
'Asia/Riyadh'=>'Arab Standard Time (Asia/Riyadh)',
'Asia/Dubai'=>'Arabian Standard Time (Asia/Dubai)',
'Asia/Baghdad'=>'Arabic Standard Time (Asia/Baghdad)',
'America/Buenos_Aires'=>'Argentina Standard Time (America/Buenos_Aires)',
'Asia/Yerevan'=>'Armenian Standard Time (Asia/Yerevan)',
'America/Halifax'=>'Atlantic Standard Time (America/Halifax)',
'Asia/Baku'=>'Azerbaijan Standard Time (Asia/Baku)',
'Atlantic/Azores'=>'Azores Standard Time (Atlantic/Azores)',
'America/Regina'=>'Canada Central Standard Time (America/Regina)',
'Atlantic/Cape_Verde'=>'Cape Verde Standard Time (Atlantic/Cape_Verde)',
'Australia/Adelaide'=>'Cen. Australia Standard Time (Australia/Adelaide)',
'America/Guatemala'=>'Central America Standard Time (America/Guatemala)',
'Asia/Dhaka'=>'Central Asia Standard Time (Asia/Dhaka)',
'America/Manaus'=>'Central Brazilian Standard Time (America/Manaus)',
'Europe/Budapest'=>'Central Europe Standard Time (Europe/Budapest)',
'Europe/Warsaw'=>'Central European Standard Time (Europe/Warsaw)',
'Pacific/Guadalcanal'=>'Central Pacific Standard Time (Pacific/Guadalcanal)',
'America/Chicago'=>'Central Standard Time (America/Chicago)',
'America/Mexico_City'=>'Central Standard Time (Mexico) (America/Mexico_City)',
'Asia/Shanghai'=>'China Standard Time (Asia/Shanghai)',
'Etc/GMT+12'=>'Dateline Standard Time (Etc/GMT+12)',
'Africa/Nairobi'=>'E. Africa Standard Time (Africa/Nairobi)',
'Australia/Brisbane'=>'E. Australia Standard Time (Australia/Brisbane)',
'Europe/Minsk'=>'E. Europe Standard Time (Europe/Minsk)',
'America/Sao_Paulo'=>'E. South America Standard Time (America/Sao_Paulo)',
'America/New_York'=>'Eastern Standard Time (America/New_York)',
'Africa/Cairo'=>'Egypt Standard Time (Africa/Cairo)',
'Asia/Yekaterinburg'=>'Ekaterinburg Standard Time (Asia/Yekaterinburg)',
'Europe/Kiev'=>'FLE Standard Time (Europe/Kiev)',
'Pacific/Fiji'=>'Fiji Standard Time (Pacific/Fiji)',
'Europe/London'=>'GMT Standard Time (Europe/London)',
'Europe/Istanbul'=>'GTB Standard Time (Europe/Istanbul)',
'Etc/GMT-3'=>'Georgian Standard Time (Etc/GMT-3)',
'America/Godthab'=>'Greenland Standard Time (America/Godthab)',
'Atlantic/Reykjavik'=>'Greenwich Standard Time (Atlantic/Reykjavik)',
'Pacific/Honolulu'=>'Hawaiian Standard Time (Pacific/Honolulu)',
'Asia/Calcutta'=>'India Standard Time (Asia/Calcutta)',
'Asia/Tehran'=>'Iran Standard Time (Asia/Tehran)',
'Asia/Jerusalem'=>'Israel Standard Time (Asia/Jerusalem)',
'Asia/Amman'=>'Jordan Standard Time (Asia/Amman)',
'Asia/Seoul'=>'Korea Standard Time (Asia/Seoul)',
'Indian/Mauritius'=>'Mauritius Standard Time (Indian/Mauritius)',
'America/Chihuahua'=>'Mexico Standard Time 2 (America/Chihuahua)',
'Atlantic/South_Georgia'=>'Mid-Atlantic Standard Time (Atlantic/South_Georgia)',
'Asia/Beirut'=>'Middle East Standard Time (Asia/Beirut)',
'America/Montevideo'=>'Montevideo Standard Time (America/Montevideo)',
'Africa/Casablanca'=>'Morocco Standard Time (Africa/Casablanca)',
'America/Denver'=>'Mountain Standard Time (America/Denver)',
'Asia/Rangoon'=>'Myanmar Standard Time (Asia/Rangoon)',
'Asia/Novosibirsk'=>'N. Central Asia Standard Time (Asia/Novosibirsk)',
'Africa/Windhoek'=>'Namibia Standard Time (Africa/Windhoek)',
'Asia/Katmandu'=>'Nepal Standard Time (Asia/Katmandu)',
'Pacific/Auckland'=>'New Zealand Standard Time (Pacific/Auckland)',
'America/St_Johns'=>'Newfoundland Standard Time (America/St_Johns)',
'Asia/Irkutsk'=>'North Asia East Standard Time (Asia/Irkutsk)',
'Asia/Krasnoyarsk'=>'North Asia Standard Time (Asia/Krasnoyarsk)',
'America/Santiago'=>'Pacific SA Standard Time (America/Santiago)',
'America/Los_Angeles'=>'Pacific Standard Time (America/Los_Angeles)',
'America/Tijuana'=>'Pacific Standard Time (Mexico) (America/Tijuana)',
'Asia/Karachi'=>'Pakistan Standard Time (Asia/Karachi)',
'Europe/Paris'=>'Romance Standard Time (Europe/Paris)',
'Europe/Moscow'=>'Russian Standard Time (Europe/Moscow)',
'Etc/GMT+3'=>'SA Eastern Standard Time (Etc/GMT+3)',
'America/Bogota'=>'SA Pacific Standard Time (America/Bogota)',
'America/La_Paz'=>'SA Western Standard Time (America/La_Paz)',
'Asia/Bangkok'=>'SE Asia Standard Time (Asia/Bangkok)',
'Pacific/Apia'=>'Samoa Standard Time (Pacific/Apia)',
'Asia/Singapore'=>'Singapore Standard Time (Asia/Singapore)',
'Africa/Johannesburg'=>'South Africa Standard Time (Africa/Johannesburg)',
'Asia/Colombo'=>'Sri Lanka Standard Time (Asia/Colombo)',
'Asia/Taipei'=>'Taipei Standard Time (Asia/Taipei)',
'Australia/Hobart'=>'Tasmania Standard Time (Australia/Hobart)',
'Asia/Tokyo'=>'Tokyo Standard Time (Asia/Tokyo)',
'Pacific/Tongatapu'=>'Tonga Standard Time (Pacific/Tongatapu)',
'Etc/GMT+5'=>'US Eastern Standard Time (Etc/GMT+5)',
'America/Phoenix'=>'US Mountain Standard Time (America/Phoenix)',
'America/Caracas'=>'Venezuela Standard Time (America/Caracas)',
'Asia/Vladivostok'=>'Vladivostok Standard Time (Asia/Vladivostok)',
'Australia/Perth'=>'W. Australia Standard Time (Australia/Perth)',
'Africa/Lagos'=>'W. Central Africa Standard Time (Africa/Lagos)',
'Europe/Berlin'=>'W. Europe Standard Time (Europe/Berlin)',
'Asia/Tashkent'=>'West Asia Standard Time (Asia/Tashkent)',
'Pacific/Port_Moresby'=>'West Pacific Standard Time (Pacific/Port_Moresby)',
'Asia/Yakutsk'=>'Yakutsk Standard Time (Asia/Yakutsk)');
?>